/** Labels for `buildPricingRowsFromApiPlan` keys (`features.*`). Use `{count}` where needed. */
export const pricingRowLabelsEn: Record<string, string> = {
  'features.units': 'Up to {count} units',
  'features.users': 'Up to {count} users',
  'features.tickets': 'Up to {count} tickets per month',
  'features.services': 'Up to {count} services',
  'features.counters': 'Up to {count} service counters',
  'features.unlimitedUnits': 'Unlimited units',
  'features.unlimitedUsers': 'Unlimited users',
  'features.unlimitedTickets': 'Unlimited tickets',
  'features.unlimitedServices': 'Unlimited services',
  'features.unlimitedCounters': 'Unlimited counters',
  'features.negotiableUnits': 'Unit capacity by agreement',
  'features.negotiableUsers': 'User seats by agreement',
  'features.negotiableTickets': 'Monthly tickets by agreement',
  'features.negotiableServices': 'Services volume by agreement',
  'features.negotiableCounters': 'Service counters by agreement',
  'features.zonesPerUnit': 'Up to {count} service zones per unit',
  'features.unlimitedZonesPerUnit': 'Unlimited service zones per unit',
  'features.negotiableZonesPerUnit': 'Service zones per unit by agreement',
  'features.realtimeUpdates': 'Real-time updates',
  'features.basicSupport': 'Basic support',
  'features.basicReports': 'Basic reports',
  'features.advancedReports': 'Advanced analytics',
  'features.emailSupport': 'Email support',
  'features.phoneSupport': 'Phone support',
  'features.apiAccess': 'API access',
  'features.customBranding': 'Custom branding',
  'features.whiteLabel': 'White-label solution',
  'features.prioritySupport': 'Priority support',
  'features.dedicatedSupport': 'Dedicated manager',
  'features.slaGuarantee': 'SLA guarantee',
  'features.customIntegrations': 'Custom integrations',
  'features.teamTraining': 'Team training'
};

export const pricingRowLabelsRu: Record<string, string> = {
  'features.units': 'До {count} подразделений',
  'features.users': 'До {count} пользователей',
  'features.tickets': 'До {count} талонов в месяц',
  'features.services': 'До {count} услуг',
  'features.counters': 'До {count} окон обслуживания',
  'features.unlimitedUnits': 'Неограниченное количество подразделений',
  'features.unlimitedUsers': 'Неограниченное количество пользователей',
  'features.unlimitedTickets': 'Неограниченное количество талонов',
  'features.unlimitedServices': 'Неограниченное количество услуг',
  'features.unlimitedCounters': 'Неограниченное количество окон',
  'features.negotiableUnits': 'Подразделения — по договорённости',
  'features.negotiableUsers': 'Пользователи — по договорённости',
  'features.negotiableTickets': 'Талоны в месяц — по договорённости',
  'features.negotiableServices': 'Объём услуг — по договорённости',
  'features.negotiableCounters': 'Окна обслуживания — по договорённости',
  'features.zonesPerUnit': 'До {count} сервисных зон на подразделение',
  'features.unlimitedZonesPerUnit': 'Неограниченное количество зон на подразделение',
  'features.negotiableZonesPerUnit': 'Зоны на подразделение — по договорённости',
  'features.realtimeUpdates': 'Обновления в реальном времени',
  'features.basicSupport': 'Базовая поддержка',
  'features.basicReports': 'Базовые отчёты',
  'features.advancedReports': 'Продвинутая аналитика',
  'features.emailSupport': 'Поддержка по email',
  'features.phoneSupport': 'Телефонная поддержка',
  'features.apiAccess': 'Доступ к API',
  'features.customBranding': 'Кастомный брендинг',
  'features.whiteLabel': 'White-label решение',
  'features.prioritySupport': 'Приоритетная поддержка',
  'features.dedicatedSupport': 'Выделенный менеджер',
  'features.slaGuarantee': 'Гарантия SLA',
  'features.customIntegrations': 'Индивидуальные интеграции',
  'features.teamTraining': 'Обучение команды'
};
